export const CHROME_TO_TESSERACT: Record<string, string> = {
  ar: 'ara',
  bg: 'bul',
  bn: 'ben',
  ca: 'cat',
  cs: 'ces',
  da: 'dan',
  de: 'deu',
  el: 'ell',
  en: 'eng',
  'en-GB': 'eng',
  'en-US': 'eng',
  es: 'spa',
  'es-419': 'spa',
  fi: 'fin',
  fr: 'fra',
  'fr-CA': 'fra',
  he: 'heb',
  hi: 'hin',
  hu: 'hun',
  id: 'ind',
  it: 'ita',
  ja: 'jpn',
  ko: 'kor',
  nb: 'nor',
  nl: 'nld',
  no: 'nor',
  pl: 'pol',
  pt: 'por',
  'pt-BR': 'por',
  'pt-PT': 'por',
  ro: 'ron',
  ru: 'rus',
  sv: 'swe',
  th: 'tha',
  tr: 'tur',
  uk: 'ukr',
  vi: 'vie',
  zh: 'chi_sim',
  'zh-CN': 'chi_sim',
  'zh-TW': 'chi_tra',
};

export const LANGUAGES = [
  { value: 'ara', label: 'Arabic' },
  { value: 'ben', label: 'Bengali' },
  { value: 'bul', label: 'Bulgarian' },
  { value: 'cat', label: 'Catalan' },
  { value: 'chi_sim', label: 'Chinese (Simp)' },
  { value: 'chi_tra', label: 'Chinese (Trad)' },
  { value: 'ces', label: 'Czech' },
  { value: 'dan', label: 'Danish' },
  { value: 'nld', label: 'Dutch' },
  { value: 'eng', label: 'English' },
  { value: 'fin', label: 'Finnish' },
  { value: 'fra', label: 'French' },
  { value: 'deu', label: 'German' },
  { value: 'ell', label: 'Greek' },
  { value: 'heb', label: 'Hebrew' },
  { value: 'hin', label: 'Hindi' },
  { value: 'hun', label: 'Hungarian' },
  { value: 'ind', label: 'Indonesian' },
  { value: 'ita', label: 'Italian' },
  { value: 'jpn', label: 'Japanese' },
  { value: 'kor', label: 'Korean' },
  { value: 'nor', label: 'Norwegian' },
  { value: 'pol', label: 'Polish' },
  { value: 'por', label: 'Portuguese' },
  { value: 'ron', label: 'Romanian' },
  { value: 'rus', label: 'Russian' },
  { value: 'spa', label: 'Spanish' },
  { value: 'swe', label: 'Swedish' },
  { value: 'tha', label: 'Thai' },
  { value: 'tur', label: 'Turkish' },
  { value: 'ukr', label: 'Ukrainian' },
  { value: 'vie', label: 'Vietnamese' },
] as const;
